### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by NehaAmbasta99** [itsksaurabh/ideaground#2]
CTA "Log in with Google", is throwing the Authorization error.
<img width="341" alt="AuthError" src="https://user-images.githubusercontent.com/19830779/90732388-a6fb5280-e2e8-11ea-9499-79d6ca59b587.PNG">

**Comment by itsksaurabh** [comment]
@NehaAmbasta99 Thank you for reporting it.
I Fixed it. Check it again so that we can close the issue. :)

**Comment by NehaAmbasta99** [comment]
It is working now. Thanks for fixing the issue. Will post my idea there 👍🏻
